site_name: 'Chippy Documentation'
theme: 'material'
extra_css:
  - 'css/styles.css'

markdown_extensions:
  - pymdownx.extra

nav:
  - SpaceUsurper:
    - Enums:
      - BulletTextAlignment: 'SpaceUsurper/BulletTextAlignment.md'
      - CoreColorType: 'SpaceUsurper/CoreColorType.md'
      - DepthLevel: 'SpaceUsurper/DepthLevel.md'
      - DespawnStyle: 'SpaceUsurper/DespawnStyle.md'
      - Direction: 'SpaceUsurper/Direction.md'
      - EasingType: 'SpaceUsurper/EasingType.md'
      - FlipPatternMode: 'SpaceUsurper/FlipPatternMode.md'
      - FloatingTextFont: 'SpaceUsurper/FloatingTextFont.md'
      - LoopMode: 'SpaceUsurper/LoopMode.md'
      - Medal: 'SpaceUsurper/Medal.md'
      - MirrorMode: 'SpaceUsurper/MirrorMode.md'
      - PartSelectMode: 'SpaceUsurper/PartSelectMode.md'
      - PixelType: 'SpaceUsurper/PixelType.md'
      - RadialDirectionMode: 'SpaceUsurper/RadialDirectionMode.md'
      - UnitFacingMode: 'SpaceUsurper/UnitFacingMode.md'
      - UnitMovementMode: 'SpaceUsurper/UnitMovementMode.md'
    - Structs:
      - DataPath: 'SpaceUsurper/DataPath.md'
      - IntRange: 'SpaceUsurper/IntRange.md'
      - LocalizedString: 'SpaceUsurper/LocalizedString.md'
      - Rotation: 'SpaceUsurper/Rotation.md'
      - StageID: 'SpaceUsurper/StageID.md'
    - Resources:
      - ActionList: 'SpaceUsurper/ActionList.md'
      - BulletData: 'SpaceUsurper/BulletData.md'
      - BulletKeyframeData: 'SpaceUsurper/BulletKeyframeData.md'
      - ButtonPromptData: 'SpaceUsurper/ButtonPromptData.md'
      - CampaignData: 'SpaceUsurper/CampaignData.md'
      - CampaignListData: 'SpaceUsurper/CampaignListData.md'
      - CoreData: 'SpaceUsurper/CoreData.md'
      - FormData: 'SpaceUsurper/FormData.md'
      - FormData+BorderWarningData: 'SpaceUsurper/FormData+BorderWarningData.md'
      - FormData+PartData: 'SpaceUsurper/FormData+PartData.md'
      - FormData+PixelJsonData: 'SpaceUsurper/FormData+PixelJsonData.md'
      - FormData+TextureData: 'SpaceUsurper/FormData+TextureData.md'
      - FormData+TextureData+ShaderData: 'SpaceUsurper/FormData+TextureData+ShaderData.md'
      - FsmData: 'SpaceUsurper/FsmData.md'
      - FuncParams: 'SpaceUsurper/FuncParams.md'
      - HotloadedData: 'SpaceUsurper/HotloadedData.md'
      - HotloadedData: 'SpaceUsurper/HotloadedData.md'
      - KeyframeProperty: 'SpaceUsurper/KeyframeProperty.md'
      - LaserData: 'SpaceUsurper/LaserData.md'
      - MovementData: 'SpaceUsurper/MovementData.md'
      - PatternData: 'SpaceUsurper/PatternData.md'
      - PhysicsElementData: 'SpaceUsurper/PhysicsElementData.md'
      - PlayerData: 'SpaceUsurper/PlayerData.md'
      - PlayerGunData: 'SpaceUsurper/PlayerGunData.md'
      - PluginData: 'SpaceUsurper/PluginData.md'
      - PropertyContainerData: 'SpaceUsurper/PropertyContainerData.md'
      - PxcAnimData: 'SpaceUsurper/PxcAnimData.md'
      - PxcSourceData: 'SpaceUsurper/PxcSourceData.md'
      - SampleFileData: 'SpaceUsurper/SampleFileData.md'
      - SfxManifestData: 'SpaceUsurper/SfxManifestData.md'
      - SongConfigData: 'SpaceUsurper/SongConfigData.md'
      - SongConfigData+LayerData: 'SpaceUsurper/SongConfigData+LayerData.md'
      - SongConfigData+LayerData+SegmentData: 'SpaceUsurper/SongConfigData+LayerData+SegmentData.md'
      - SpriteData: 'SpaceUsurper/SpriteData.md'
      - StageData: 'SpaceUsurper/StageData.md'
      - StageData+ArenaData: 'SpaceUsurper/StageData+ArenaData.md'
      - StageData+MedalData: 'SpaceUsurper/StageData+MedalData.md'
      - StageData+PlayerData: 'SpaceUsurper/StageData+PlayerData.md'
      - StageMenuData: 'SpaceUsurper/StageMenuData.md'
      - StatusEffectCategoryData: 'SpaceUsurper/StatusEffectCategoryData.md'
      - StatusEffectData: 'SpaceUsurper/StatusEffectData.md'
      - StatusEffectData+PlayerModifierData: 'SpaceUsurper/StatusEffectData+PlayerModifierData.md'
      - SubroutineData: 'SpaceUsurper/SubroutineData.md'
      - UnitData: 'SpaceUsurper/UnitData.md'
    - Classes:
      - AnimatedSpriteController: 'SpaceUsurper/AnimatedSpriteController.md'
      - Bullet: 'SpaceUsurper/Bullet.md'
      - BulletPattern: 'SpaceUsurper/BulletPattern.md'
      - Drawable: 'SpaceUsurper/Drawable.md'
      - EaseTestStage: 'SpaceUsurper/EaseTestStage.md'
      - GameStage: 'SpaceUsurper/GameStage.md'
      - IPositional: 'SpaceUsurper/IPositional.md'
      - IPropertyContainer: 'SpaceUsurper/IPropertyContainer.md'
      - Laser: 'SpaceUsurper/Laser.md'
      - MenuStage: 'SpaceUsurper/MenuStage.md'
      - MovementController: 'SpaceUsurper/MovementController.md'
      - PixelData: 'SpaceUsurper/PixelData.md'
      - PixelGroup: 'SpaceUsurper/PixelGroup.md'
      - Player: 'SpaceUsurper/Player.md'
      - Player_Body: 'SpaceUsurper/Player_Body.md'
      - Player_Guns: 'SpaceUsurper/Player_Guns.md'
      - Player_Health: 'SpaceUsurper/Player_Health.md'
      - Player_Input: 'SpaceUsurper/Player_Input.md'
      - Player_StatusEffects: 'SpaceUsurper/Player_StatusEffects.md'
      - Player_Vibration: 'SpaceUsurper/Player_Vibration.md'
      - PlayerComponent: 'SpaceUsurper/PlayerComponent.md'
      - PlayerGun: 'SpaceUsurper/PlayerGun.md'
      - ProgressionManager: 'SpaceUsurper/ProgressionManager.md'
      - Rand: 'SpaceUsurper/Rand.md'
      - RotationController: 'SpaceUsurper/RotationController.md'
      - Song: 'SpaceUsurper/Song.md'
      - SongLayer: 'SpaceUsurper/SongLayer.md'
      - Stage: 'SpaceUsurper/Stage.md'
      - Stage_Behaviour: 'SpaceUsurper/Stage_Behaviour.md'
      - Stage_Camera: 'SpaceUsurper/Stage_Camera.md'
      - Stage_Song: 'SpaceUsurper/Stage_Song.md'
      - Stage_Speech: 'SpaceUsurper/Stage_Speech.md'
      - Stage_Text: 'SpaceUsurper/Stage_Text.md'
      - Stage_TimeScale: 'SpaceUsurper/Stage_TimeScale.md'
      - Stage_Units: 'SpaceUsurper/Stage_Units.md'
      - StatusEffect: 'SpaceUsurper/StatusEffect.md'
      - Unit: 'SpaceUsurper/Unit.md'
  - SpaceUsurper.UI:
    - Classes:
      - SpeechBubble: 'SpaceUsurper.UI/SpeechBubble.md'

