site_name: Chippy Documentation
theme: readthedocs

nav:
- SpaceUsurper:
  - Class:
    - Bullet: 'SpaceUsurper.Bullet.md'
    - PropertyData: 'SpaceUsurper.PropertyData.md'
    - Unit: 'SpaceUsurper.Unit.md'
    - PixelGroup: 'SpaceUsurper.PixelGroup.md'
    - Laser: 'SpaceUsurper.Laser.md'
    - BulletPattern: 'SpaceUsurper.BulletPattern.md'
    - PxcFrameData: 'SpaceUsurper.PxcFrameData.md'
    - SpriteAnimData: 'SpaceUsurper.SpriteAnimData.md'
    - PixelData: 'SpaceUsurper.PixelData.md'
    - MovementController: 'SpaceUsurper.MovementController.md'
    - AnimatedSpriteController: 'SpaceUsurper.AnimatedSpriteController.md'
    - RotationController: 'SpaceUsurper.RotationController.md'
    - ProgressionManager: 'SpaceUsurper.ProgressionManager.md'
    - CampaignStageData: 'SpaceUsurper.CampaignStageData.md'
    - Player_Body: 'SpaceUsurper.Player_Body.md'
    - Player_Guns: 'SpaceUsurper.Player_Guns.md'
    - PlayerGun: 'SpaceUsurper.PlayerGun.md'
    - Player_Health: 'SpaceUsurper.Player_Health.md'
    - Player_Input: 'SpaceUsurper.Player_Input.md'
    - Player_StatusEffects: 'SpaceUsurper.Player_StatusEffects.md'
    - Player_Vibration: 'SpaceUsurper.Player_Vibration.md'
    - Player: 'SpaceUsurper.Player.md'
    - StatusEffect: 'SpaceUsurper.StatusEffect.md'
    - Rand: 'SpaceUsurper.Rand.md'
    - Song: 'SpaceUsurper.Song.md'
    - SongLayer: 'SpaceUsurper.SongLayer.md'
    - EaseTestStage: 'SpaceUsurper.EaseTestStage.md'
    - Stage_Behaviour: 'SpaceUsurper.Stage_Behaviour.md'
    - Stage_Camera: 'SpaceUsurper.Stage_Camera.md'
    - Stage_Song: 'SpaceUsurper.Stage_Song.md'
    - Stage_Speech: 'SpaceUsurper.Stage_Speech.md'
    - IPositional: 'SpaceUsurper.IPositional.md'
    - Stage_Text: 'SpaceUsurper.Stage_Text.md'
    - Stage_TimeScale: 'SpaceUsurper.Stage_TimeScale.md'
    - Stage_Units: 'SpaceUsurper.Stage_Units.md'
    - GameStage: 'SpaceUsurper.GameStage.md'
    - MenuStage: 'SpaceUsurper.MenuStage.md'
    - Stage: 'SpaceUsurper.Stage.md'
    - IPropertyContainer: 'SpaceUsurper.IPropertyContainer.md'
  - Struct:
    - DataPath: 'SpaceUsurper.DataPath.md'
    - Rotation: 'SpaceUsurper.Rotation.md'
    - IntRect: 'SpaceUsurper.IntRect.md'
    - LocalizedString: 'SpaceUsurper.LocalizedString.md'
    - PxcAnimDataCompressed: 'SpaceUsurper.PxcAnimDataCompressed.md'
    - PxcSourceDataCompressed: 'SpaceUsurper.PxcSourceDataCompressed.md'
    - PxcPixelImportData: 'SpaceUsurper.PxcPixelImportData.md'
    - IntRange: 'SpaceUsurper.IntRange.md'
    - TimerHandle: 'SpaceUsurper.TimerHandle.md'
    - StageID: 'SpaceUsurper.StageID.md'
  - Resource:
    - BulletData: 'SpaceUsurper.BulletData.md'
    - KeyframeProperty: 'SpaceUsurper.KeyframeProperty.md'
    - PatternData: 'SpaceUsurper.PatternData.md'
    - FsmData: 'SpaceUsurper.FsmData.md'
    - ActionList: 'SpaceUsurper.ActionList.md'
    - StatusEffectData: 'SpaceUsurper.StatusEffectData.md'
    - StatusEffectCategoryData: 'SpaceUsurper.StatusEffectCategoryData.md'
    - StatusEffectData+PlayerModifierData: 'SpaceUsurper.StatusEffectData+PlayerModifierData.md'
    - BulletKeyframeData: 'SpaceUsurper.BulletKeyframeData.md'
    - CoreData: 'SpaceUsurper.CoreData.md'
    - FormData: 'SpaceUsurper.FormData.md'
    - FormData+AnimData: 'SpaceUsurper.FormData+AnimData.md'
    - PxcAnimData: 'SpaceUsurper.PxcAnimData.md'
    - FormData+PartData: 'SpaceUsurper.FormData+PartData.md'
    - FormData+BorderWarningData: 'SpaceUsurper.FormData+BorderWarningData.md'
    - LaserData: 'SpaceUsurper.LaserData.md'
    - FormData+PartData+PlacementData: 'SpaceUsurper.FormData+PartData+PlacementData.md'
    - SpriteData: 'SpaceUsurper.SpriteData.md'
    - FormData+PixelJsonData: 'SpaceUsurper.FormData+PixelJsonData.md'
    - PxcSourceData: 'SpaceUsurper.PxcSourceData.md'
    - FormData+RepulsionCircleData: 'SpaceUsurper.FormData+RepulsionCircleData.md'
    - FormData+TextureData: 'SpaceUsurper.FormData+TextureData.md'
    - FormData+TextureData+ShaderData: 'SpaceUsurper.FormData+TextureData+ShaderData.md'
    - UnitData: 'SpaceUsurper.UnitData.md'
    - MovementData: 'SpaceUsurper.MovementData.md'
    - PhysicsElementData: 'SpaceUsurper.PhysicsElementData.md'
    - CampaignData: 'SpaceUsurper.CampaignData.md'
    - StageData: 'SpaceUsurper.StageData.md'
    - StageData+ArenaData: 'SpaceUsurper.StageData+ArenaData.md'
    - StageData+MedalData: 'SpaceUsurper.StageData+MedalData.md'
    - StageData+PlayerData: 'SpaceUsurper.StageData+PlayerData.md'
    - PlayerData: 'SpaceUsurper.PlayerData.md'
    - PlayerGunData: 'SpaceUsurper.PlayerGunData.md'
    - SongConfigData: 'SpaceUsurper.SongConfigData.md'
    - SongConfigData+LayerData: 'SpaceUsurper.SongConfigData+LayerData.md'
    - SongConfigData+LayerData+SegmentData: 'SpaceUsurper.SongConfigData+LayerData+SegmentData.md'
    - StageData+UnitData: 'SpaceUsurper.StageData+UnitData.md'
    - StageData+UnitData+RequirementData: 'SpaceUsurper.StageData+UnitData+RequirementData.md'
  - Enum:
    - EasingType: 'SpaceUsurper.EasingType.md'
    - KeyframePropertyMode: 'SpaceUsurper.KeyframePropertyMode.md'
    - DepthLevel: 'SpaceUsurper.DepthLevel.md'
    - DespawnStyle: 'SpaceUsurper.DespawnStyle.md'
    - PatternAimMode: 'SpaceUsurper.PatternAimMode.md'
    - PatternShape: 'SpaceUsurper.PatternShape.md'
    - BulletFacingMode: 'SpaceUsurper.BulletFacingMode.md'
    - BulletMoveMode: 'SpaceUsurper.BulletMoveMode.md'
    - BulletVelocityMode: 'SpaceUsurper.BulletVelocityMode.md'
    - ShapeType: 'SpaceUsurper.ShapeType.md'
    - MirrorMode: 'SpaceUsurper.MirrorMode.md'
    - FloatingTextFont: 'SpaceUsurper.FloatingTextFont.md'
    - BulletTextAlignment: 'SpaceUsurper.BulletTextAlignment.md'
    - FlipPatternMode: 'SpaceUsurper.FlipPatternMode.md'
    - CoreColorType: 'SpaceUsurper.CoreColorType.md'
    - LoopMode: 'SpaceUsurper.LoopMode.md'
    - UnitFacingMode: 'SpaceUsurper.UnitFacingMode.md'
    - UnitMovementMode: 'SpaceUsurper.UnitMovementMode.md'
    - PixelJsonTransformation: 'SpaceUsurper.PixelJsonTransformation.md'
    - PixelType: 'SpaceUsurper.PixelType.md'
    - PartSelectMode: 'SpaceUsurper.PartSelectMode.md'
    - Direction: 'SpaceUsurper.Direction.md'
    - SmallArenaCameraClampingMode: 'SpaceUsurper.SmallArenaCameraClampingMode.md'
    - GameMode: 'SpaceUsurper.GameMode.md'
    - Medal: 'SpaceUsurper.Medal.md'
    - RadialDirectionMode: 'SpaceUsurper.RadialDirectionMode.md'
- SpaceUsurper.UI:
  - Class:
    - SpeechBubble: 'SpaceUsurper.UI.SpeechBubble.md'
- GameAnalyticsSDK:
  - Enum:
    - GAProgressionStatus: 'GameAnalyticsSDK.GAProgressionStatus.md'

